server {
  listen 3000;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  # Resolver for dynamic DNS lookup (kube-dns)
  resolver kube-dns.kube-system.svc.cluster.local valid=10s;
  set $upstream_api_gateway "api-gateway.crickethub.svc.cluster.local:8080";

  location /api/ {
    proxy_pass http://$upstream_api_gateway/api/;
    proxy_set_header Host $host;
    proxy_set_header Authorization $http_authorization;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
