apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crickethub-ingress
  namespace: crickethub
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: crickethub.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service: { name: api-gateway, port: { number: 8080 } }
          - path: /
            pathType: Prefix
            backend:
              service: { name: frontend, port: { number: 3000 } }
