apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: crickethub-prod
resources:
  - ../../base
labels:
  - pairs:
      environment: prod
      app.kubernetes.io/environment: prod
images:
  - name: 114268015259.dkr.ecr.ap-south-1.amazonaws.com/crickethub/frontend
    newTag: prod
  - name: 114268015259.dkr.ecr.ap-south-1.amazonaws.com/crickethub/api-gateway
    newTag: prod
  - name: 114268015259.dkr.ecr.ap-south-1.amazonaws.com/crickethub/auth-service
    newTag: prod
  - name: 114268015259.dkr.ecr.ap-south-1.amazonaws.com/crickethub/team-service
    newTag: prod
  - name: 114268015259.dkr.ecr.ap-south-1.amazonaws.com/crickethub/match-service
    newTag: prod
  - name: 114268015259.dkr.ecr.ap-south-1.amazonaws.com/crickethub/scoring-service
    newTag: prod
  - name: 114268015259.dkr.ecr.us-east-1.amazonaws.com/prediction-service
    newTag: prod
patches:
  - target:
      kind: Ingress
      name: crickethub-ingress
    patch: |-
      - op: replace
        path: /metadata/name
        value: crickethub-prod-ingress
      - op: replace
        path: /metadata/annotations/alb.ingress.kubernetes.io~1load-balancer-name
        value: crickethub-prod-alb
      - op: replace
        path: /metadata/annotations/alb.ingress.kubernetes.io~1group.name
        value: crickethub-prod
      - op: replace
        path: /metadata/annotations/alb.ingress.kubernetes.io~1tags
        value: Environment=prod,App=crickethub
  - target:
      kind: Deployment
      name: frontend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      kind: Deployment
      name: api-gateway
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      kind: Deployment
      name: auth-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: Deployment
      name: team-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: Deployment
      name: match-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: Deployment
      name: scoring-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: Deployment
      name: prediction-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
