apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - database/postgres.yaml
  - gateway/api-gateway.yaml
  - frontend/frontend.yaml
  - services/backend-services.yaml
  - ingress/ingress.yaml

commonLabels:
  app.kubernetes.io/name: crickethub
  app.kubernetes.io/part-of: crickethub
